#!/bin/bash
set -e

echo -e "\033[1;33m-->\033[1;34m Launching updater 🍵\033[0m"
GNS_FROM_HOST=true /nix/var/nix/profiles/default/bin/nix develop --refresh --accept-flake-config gitlab:garuda-linux/garuda-nix-subsystem/stable#gns-update -c "gns-update"