#!/bin/bash -e

all=0
lines=()

while read -r line; do
	if [[ "${line}" != */vmlinuz ]]; then
		# triggers when it's a change to dracut files
		all=1
		continue
	fi

	lines+=("/${line%/vmlinuz}")

	pkgbase="$(<"${lines[-1]}/pkgbase")"
	install -Dm644 "/${line}" "/boot/vmlinuz-${pkgbase}"
done

if ((all)); then
	lines=(/usr/lib/modules/*)
fi

status=0
for line in "${lines[@]}"; do
	if ! pacman -Qqo "${line}/pkgbase" &>/dev/null; then
		# if pkgbase does not belong to any package then skip this kernel
		continue
	fi

	pkgbase="$(<"${line}/pkgbase")"
	kver="${line##*/}"

	set +e
	(
		set -e
		echo ":: Building initramfs for ${pkgbase} (${kver})"
		dracut -L 3 --force "/boot/initramfs-${pkgbase}.img" "${kver}"

		echo ":: Building fallback initramfs for ${pkgbase} (${kver})"
		dracut -L 1 --force --no-hostonly -o "network" "/boot/initramfs-${pkgbase}-fallback.img" "${kver}"
	)
	_status="$?"
	# only accumulates error status
	[ "$_status" = 0 ] || status="$_status"
	set +e
done

exit "$status"