#!/bin/bash

post_upgrade() {
	if [[ -f "/usr/lib/garuda/garuda.shlib" ]] && [[ $(vercmp 1:r62.889aefa-6 "$2") -gt 0 ]]; then
		# shellcheck disable=SC1091
		. /usr/lib/garuda/garuda.shlib
		garudalib_add_update_notice "If you are experiencing issues such as flickering when recording in OBS or windows missing when taking screenshots, you can now uninstall xf86-video-intel: sudo pacman -R xf86-video-intel"
	fi
}
