#!/bin/sh
# arg 1:  the new package version
# arg 2:  the old package version

local_config_dir="/var/lib/mhwd/local/pci"
db_config_dir="/var/lib/mhwd/db/pci"

err() {
	ALL_OFF="\e[1;0m"
	BOLD="\e[1;1m"
	RED="${BOLD}\e[1;31m"
	local mesg=$1
	shift
	printf "${RED}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

msg() {
	ALL_OFF="\e[1;0m"
	BOLD="\e[1;1m"
	GREEN="${BOLD}\e[1;32m"
	local mesg=$1
	shift
	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

# $1: old config name
# $2: new config name
# $3: new config path
rename_config() {
	if [ -e "${local_config_dir}/${1}/MHWDCONFIG" ]; then
		msg "Renaming config: '${local_config_dir}/${1}'"
		mkdir -p ${local_config_dir}/${2}
		cp -f ${db_config_dir}/graphic_drivers/${3}/MHWDCONFIG ${local_config_dir}/${2}/MHWDCONFIG
		rm -Rf ${local_config_dir}/${1}
	fi
}

update_configs() {
	local_configs=$(ls ${local_config_dir})
	db_configs="$(ls ${db_config_dir}/graphic_drivers) $(ls ${db_config_dir}/network_drivers)"

	# Rename old configs
	rename_config "video-hybrid-amd-nvidia-dkms-prime-render-offloading" "video-nvidia-prime-render-offload" "nvidia-prime-render-offload"
	rename_config "video-hybrid-intel-nvidia-dkms-prime-render-offloading" "video-nvidia-prime-render-offload" "nvidia-prime-render-offload"
	rename_config "video-hybrid-amd-chaotic-nvidia-dev-dkms-tkg-prime-render-offloading" "video-chaotic-nvidia-dev-tkg-prime-render-offload" "chaotic-nvidia-dev-tkg-prime-render-offload"
	rename_config "video-hybrid-intel-chaotic-nvidia-dev-dkms-tkg-prime-render-offloading" "video-chaotic-nvidia-dev-tkg-prime-render-offload" "chaotic-nvidia-dev-tkg-prime-render-offload"
	rename_config "video-hybrid-amd-chaotic-nvidia-dkms-tkg-prime-render-offloading" "video-chaotic-nvidia-tkg-prime-render-offload" "chaotic-nvidia-tkg-prime-render-offload"
	rename_config "video-hybrid-intel-chaotic-nvidia-dkms-tkg-prime-render-offloading" "video-chaotic-nvidia-tkg-prime-render-offload" "chaotic-nvidia-tkg-prime-render-offload"
}

post_upgrade() {
	update_configs
}
