post_install() {
	systemctl enable btrfs-balance.timer btrfs-defrag.timer btrfs-scrub.timer btrfs-trim.timer garuda-pacman-lock
}

post_upgrade() {
	if (( $(vercmp $2 2.8.1-2) < 0)); then
		post_install
	fi
}

pre_remove() {
	systemctl disable garuda-pacman-lock
	echo -e "\033[1;31mTimers btrfs-balance.timer, btrfs-defrag.timer, btrfs-scrub.timer and btrfs-trim.timer will not be disabled automatically.\0033[0m"
}